# Generated by Django 3.1rc1 on 2020-09-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt', '0004_auto_20200920_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
