# Generated by Django 3.1rc1 on 2020-09-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt', '0005_stock_export_to_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
