# Generated by Django 3.1rc1 on 2020-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt', '0006_remove_stock_export_to_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
