# Generated by Django 3.1rc1 on 2020-09-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt', '0008_auto_20200922_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
