# Generated by Django 3.1rc1 on 2020-09-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_mgmt', '0011_auto_20200922_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
